package com.fingress.migration;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static com.fingress.migration.Model.*;

class SqlParserTest {
    Parsed parse(String sql) { return new SqlParser(Dialect.ORACLE, Dialect.POSTGRESQL).parse(sql); }
    @Test void convertsDateWithoutLosingTimeAndNumericPrecision() {
        Parsed parsed = parse("CREATE TABLE customers (id NUMBER(12,2), joined DATE, name VARCHAR2(100 CHAR));");
        assertTrue(parsed.issues().isEmpty(), parsed.issues().toString());
        String sql = SqlWriter.create(parsed.tables().getFirst(), "public", Dialect.POSTGRESQL);
        assertTrue(sql.contains("NUMERIC(12,2)")); assertTrue(sql.contains("TIMESTAMP(0)")); assertTrue(sql.contains("VARCHAR(100)"));
    }
    @Test void preservesCommentsSemicolonsAndEscapedQuotesInsideStrings() {
        Parsed parsed = parse("/* outer /* nested */ */ CREATE TABLE t (v VARCHAR2(100)); -- comment\nINSERT INTO t VALUES ('Oracle; -- isn''t /* SQL */');");
        assertTrue(parsed.issues().isEmpty(), parsed.issues().toString());
        assertEquals("'Oracle; -- isn''t /* SQL */'", parsed.inserts().getFirst().rows().getFirst().getFirst().sql());
    }
    @Test void preservesQuotedCaseAndFoldsUnquotedIdentifiers() {
        Parsed parsed = parse("CREATE TABLE \"Customer\" (\"DisplayName\" VARCHAR2(20), ID NUMBER(5));");
        String sql = SqlWriter.create(parsed.tables().getFirst(), "public", Dialect.POSTGRESQL);
        assertTrue(sql.contains("\"Customer\"")); assertTrue(sql.contains("\"DisplayName\"")); assertTrue(sql.contains("\"id\""));
    }
    @Test void rejectsUnknownStatementsInsteadOfDroppingThem() {
        Parsed parsed = parse("CREATE TABLE t (id NUMBER(5)); DROP TABLE users; ALTER TABLE t ADD CHECK (id > 0);");
        assertEquals(2, parsed.issues().size());
    }
    @Test void rejectsTrailingStorageClausesAndSupportsCheckConstraints() {
        assertFalse(parse("CREATE TABLE t (id NUMBER) TABLESPACE secret").issues().isEmpty());
        assertTrue(parse("CREATE TABLE t (id NUMBER CHECK (id > 0))").issues().isEmpty());
    }
    @Test void rejectsMalformedStringsAndNumbers() {
        assertFalse(parse("CREATE TABLE t (v VARCHAR2(10)); INSERT INTO t VALUES ('oops)").issues().isEmpty());
        assertFalse(parse("CREATE TABLE t (v NUMBER); INSERT INTO t VALUES (1e)").issues().isEmpty());
    }
    @Test void rejectsEmptyStringsWhenTargetIsOracle() {
        Parsed parsed = new SqlParser(Dialect.POSTGRESQL, Dialect.ORACLE).parse("CREATE TABLE t (v VARCHAR(10)); INSERT INTO t VALUES ('');");
        assertTrue(parsed.issues().stream().anyMatch(s -> s.contains("Empty string")));
    }
    @Test void rejectsUnboundedPostgresNumericForOracle() {
        assertFalse(new SqlParser(Dialect.POSTGRESQL, Dialect.ORACLE).parse("CREATE TABLE t (v NUMERIC)").issues().isEmpty());
    }
    @Test void primaryKeyMakesColumnNotNullableRegardlessOfIdentifierCase() {
        Parsed parsed = parse("CREATE TABLE t (id NUMBER(10), PRIMARY KEY (ID))");
        assertTrue(parsed.issues().isEmpty()); assertFalse(parsed.tables().getFirst().columns().getFirst().nullable());
    }
    @Test void rejectsDuplicateColumnsAndMissingInsertMetadata() {
        assertFalse(parse("CREATE TABLE t (id NUMBER, ID NUMBER)").issues().isEmpty());
        assertFalse(parse("INSERT INTO t (id) VALUES (1)").issues().isEmpty());
    }
    @Test void rejectsMismatchedInsertColumnCounts() {
        assertFalse(parse("CREATE TABLE t (id NUMBER, v NUMBER); INSERT INTO t VALUES (1)").issues().isEmpty());
    }
    @Test void supportsMultirowInsertAndForeignKeys() {
        Parsed parsed = parse("CREATE TABLE parent (id NUMBER(10) PRIMARY KEY); CREATE TABLE child (id NUMBER(10), CONSTRAINT fk FOREIGN KEY (id) REFERENCES parent(id)); INSERT INTO parent VALUES (1),(2);");
        assertTrue(parsed.issues().isEmpty(), parsed.issues().toString()); assertEquals(2, parsed.inserts().getFirst().rows().size());
        assertTrue(SqlWriter.afterData(parsed.tables().get(1), "public", Dialect.POSTGRESQL).getFirst().contains("REFERENCES \"public\".\"parent\""));
    }
    @Test void rejectsMultipleSourceSchemas() {
        assertFalse(parse("CREATE TABLE a.t (id NUMBER); INSERT INTO b.t VALUES (1)").issues().isEmpty());
    }
    @Test void mapsIdentityToIntegerCompatiblePostgresType() {
        Parsed parsed = parse("CREATE TABLE t (id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY)");
        assertTrue(parsed.issues().isEmpty(), parsed.issues().toString()); assertEquals("BIGINT", parsed.tables().getFirst().columns().getFirst().type().kind());
    }
    @Test void doesNotDiscardUnknownTypeModifiers() { assertFalse(parse("CREATE TABLE t (v INTEGER(8))").issues().isEmpty()); }
    @Test void recognizesOracleJdbcTimestampPrecisionAndZone() {
        assertEquals(new Type("TIMESTAMPTZ", 6, null), SqlParser.catalogType("TIMESTAMP(6) WITH TIME ZONE", 0, 0, Dialect.ORACLE));
        assertEquals(new Type("TIMESTAMP", 3, null), SqlParser.catalogType("TIMESTAMP(3)", 0, 0, Dialect.ORACLE));
        assertThrows(IllegalArgumentException.class, () -> SqlParser.catalogType("TIMESTAMP(9) WITH TIME ZONE", 0, 0, Dialect.ORACLE).target(Dialect.POSTGRESQL));
        assertThrows(IllegalArgumentException.class, () -> SqlParser.catalogType("TIMESTAMP(6) WITH LOCAL TIME ZONE", 0, 0, Dialect.ORACLE));
    }
}
