/* ============================================================
   ORACLE → POSTGRESQL CONVERTER TEST SCRIPT
   DDL + DML EDGE CASES
   ============================================================ */


/* ============================================================
   1. BASIC TABLE + ORACLE DATA TYPES
   ============================================================ */

CREATE TABLE EMPLOYEE (
    EMP_ID          NUMBER(10) PRIMARY KEY,
    EMP_NAME        VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(150),
    SALARY          NUMBER(12,2),
    BONUS           NUMBER,
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    JOIN_DATE       DATE,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    DESCRIPTION     CLOB,
    PROFILE_DATA    BLOB
);


/* ============================================================
   2. NUMBER EDGE CASES
   ============================================================ */

CREATE TABLE NUMBER_TEST (
    ID              NUMBER PRIMARY KEY,
    INT_VALUE       NUMBER(10),
    DECIMAL_VALUE   NUMBER(10,2),
    LARGE_NUMBER    NUMBER(38),
    NO_PRECISION    NUMBER,
    NEGATIVE_VALUE  NUMBER(20,5)
);


/* ============================================================
   3. DATE / TIMESTAMP EDGE CASES
   ============================================================ */

CREATE TABLE DATE_TEST (
    ID              NUMBER PRIMARY KEY,
    DATE_COL        DATE,
    TIMESTAMP_COL   TIMESTAMP,
    TS_TZ_COL       TIMESTAMP WITH TIME ZONE,
    TS_LOCAL_COL    TIMESTAMP WITH LOCAL TIME ZONE
);


/* ============================================================
   4. DEFAULT VALUES
   ============================================================ */

CREATE TABLE DEFAULT_TEST (
    ID              NUMBER PRIMARY KEY,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_DATE    DATE DEFAULT SYSDATE,
    CREATED_TS      TIMESTAMP DEFAULT SYSTIMESTAMP,
    FLAG            CHAR(1) DEFAULT 'Y',
    COUNTER         NUMBER DEFAULT 0
);


/* ============================================================
   5. IDENTITY COLUMN
   ============================================================ */

CREATE TABLE IDENTITY_TEST (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_IDENTITY_TEST PRIMARY KEY (ID)
);


/* ============================================================
   6. GENERATED ALWAYS IDENTITY
   ============================================================ */

CREATE TABLE IDENTITY_ALWAYS_TEST (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(100)
);


/* ============================================================
   7. CONSTRAINTS
   ============================================================ */

CREATE TABLE DEPARTMENT (
    DEPT_ID     NUMBER(10),
    DEPT_NAME   VARCHAR2(100) NOT NULL,
    LOCATION    VARCHAR2(100),

    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPT_NAME),
    CONSTRAINT CK_DEPARTMENT_NAME CHECK (LENGTH(DEPT_NAME) > 0)
);


/* ============================================================
   8. FOREIGN KEY
   ============================================================ */

CREATE TABLE EMPLOYEE_DEPARTMENT (
    EMP_ID      NUMBER(10),
    DEPT_ID     NUMBER(10),

    CONSTRAINT FK_EMPLOYEE
        FOREIGN KEY (EMP_ID)
        REFERENCES EMPLOYEE(EMP_ID),

    CONSTRAINT FK_DEPARTMENT
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);


/* ============================================================
   9. COMPOSITE PRIMARY KEY
   ============================================================ */

CREATE TABLE EMPLOYEE_PROJECT (
    EMP_ID      NUMBER(10),
    PROJECT_ID  NUMBER(10),
    ROLE_NAME   VARCHAR2(100),

    CONSTRAINT PK_EMP_PROJECT
        PRIMARY KEY (EMP_ID, PROJECT_ID)
);


/* ============================================================
   10. COMPOSITE UNIQUE CONSTRAINT
   ============================================================ */

CREATE TABLE USER_ACCOUNT (
    ID              NUMBER PRIMARY KEY,
    USERNAME        VARCHAR2(100),
    EMAIL           VARCHAR2(150),

    CONSTRAINT UQ_USERNAME_EMAIL
        UNIQUE (USERNAME, EMAIL)
);


/* ============================================================
   11. ALTER TABLE - ADD COLUMN
   ============================================================ */

ALTER TABLE EMPLOYEE
ADD PHONE_NUMBER VARCHAR2(20);


/* ============================================================
   12. ALTER TABLE - ADD MULTIPLE COLUMNS
   ============================================================ */

ALTER TABLE EMPLOYEE
ADD (
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(100),
    PINCODE VARCHAR2(10)
);


/* ============================================================
   13. ALTER TABLE - MODIFY COLUMN
   ============================================================ */

ALTER TABLE EMPLOYEE
MODIFY EMP_NAME VARCHAR2(200);


/* ============================================================
   14. ALTER TABLE - RENAME COLUMN
   ============================================================ */

ALTER TABLE EMPLOYEE
RENAME COLUMN PHONE_NUMBER TO MOBILE_NUMBER;


/* ============================================================
   15. ALTER TABLE - DROP COLUMN
   ============================================================ */

ALTER TABLE EMPLOYEE
DROP COLUMN PINCODE;


/* ============================================================
   16. ADD CONSTRAINT AFTER TABLE CREATION
   ============================================================ */

ALTER TABLE EMPLOYEE
ADD CONSTRAINT UQ_EMPLOYEE_EMAIL UNIQUE (EMAIL);


/* ============================================================
   17. CHECK CONSTRAINT
   ============================================================ */

ALTER TABLE EMPLOYEE
ADD CONSTRAINT CK_EMPLOYEE_SALARY
CHECK (SALARY >= 0);


/* ============================================================
   18. INDEX
   ============================================================ */

CREATE INDEX IDX_EMPLOYEE_NAME
ON EMPLOYEE (EMP_NAME);


/* ============================================================
   19. UNIQUE INDEX
   ============================================================ */

CREATE UNIQUE INDEX IDX_EMPLOYEE_EMAIL
ON EMPLOYEE (EMAIL);


/* ============================================================
   20. FUNCTION-BASED INDEX
   ============================================================ */

CREATE INDEX IDX_EMPLOYEE_UPPER_NAME
ON EMPLOYEE (UPPER(EMP_NAME));


/* ============================================================
   21. MULTI-COLUMN INDEX
   ============================================================ */

CREATE INDEX IDX_EMPLOYEE_DEPT_NAME
ON EMPLOYEE (DEPT_ID, EMP_NAME);


/* ============================================================
   22. QUOTED IDENTIFIERS
   ============================================================ */

CREATE TABLE "EmployeeDetails" (
    "EmployeeId" NUMBER PRIMARY KEY,
    "EmployeeName" VARCHAR2(100),
    "EmailAddress" VARCHAR2(150)
);


/* ============================================================
   23. RESERVED WORD AS COLUMN
   ============================================================ */

CREATE TABLE RESERVED_WORD_TEST (
    ID NUMBER PRIMARY KEY,
    "USER" VARCHAR2(100),
    "ORDER" NUMBER,
    "DATE" DATE,
    "STATUS" VARCHAR2(20)
);


/* ============================================================
   24. LONG VARCHAR / CLOB
   ============================================================ */

CREATE TABLE TEXT_TEST (
    ID NUMBER PRIMARY KEY,
    SHORT_TEXT VARCHAR2(4000),
    LONG_TEXT CLOB,
    XML_TEXT CLOB
);


/* ============================================================
   25. RAW / BLOB
   ============================================================ */

CREATE TABLE BINARY_TEST (
    ID NUMBER PRIMARY KEY,
    RAW_DATA RAW(2000),
    BLOB_DATA BLOB
);


/* ============================================================
   26. SAMPLE DATA - BASIC INSERT
   ============================================================ */

INSERT INTO DEPARTMENT
    (DEPT_ID, DEPT_NAME, LOCATION)
VALUES
    (1, 'Engineering', 'Chennai');


INSERT INTO DEPARTMENT
    (DEPT_ID, DEPT_NAME, LOCATION)
VALUES
    (2, 'HR', 'Bangalore');


/* ============================================================
   27. INSERT WITH NULL
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, EMAIL, SALARY, BONUS, IS_ACTIVE, JOIN_DATE)
VALUES
    (101, 'Vignesh', 'vignesh@example.com', 50000, NULL, 'Y', DATE '2026-01-15');


/* ============================================================
   28. INSERT WITH SYSDATE
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, EMAIL, SALARY, JOIN_DATE)
VALUES
    (102, 'Arun', 'arun@example.com', 60000, SYSDATE);


/* ============================================================
   29. INSERT WITH SYSTIMESTAMP
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, CREATED_AT)
VALUES
    (103, 'Kumar', SYSTIMESTAMP);


/* ============================================================
   30. MULTI-ROW INSERT - ORACLE INSERT ALL
   ============================================================ */

INSERT ALL
    INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION)
        VALUES (10, 'Finance', 'Chennai')
    INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION)
        VALUES (11, 'Marketing', 'Mumbai')
    INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION)
        VALUES (12, 'Operations', 'Delhi')
SELECT 1 FROM DUAL;


/* ============================================================
   31. CONDITIONAL INSERT ALL
   ============================================================ */

INSERT ALL
    WHEN SALARY >= 50000 THEN
        INTO EMPLOYEE (EMP_ID, EMP_NAME, SALARY)
        VALUES (201, 'High Salary Employee', SALARY)

    WHEN SALARY < 50000 THEN
        INTO EMPLOYEE (EMP_ID, EMP_NAME, SALARY)
        VALUES (202, 'Low Salary Employee', SALARY)

SELECT 55000 AS SALARY
FROM DUAL;


/* ============================================================
   32. INSERT FIRST
   ============================================================ */

INSERT FIRST
    WHEN SALARY >= 100000 THEN
        INTO EMPLOYEE (EMP_ID, EMP_NAME, SALARY)
        VALUES (301, 'Senior Employee', SALARY)

    WHEN SALARY >= 50000 THEN
        INTO EMPLOYEE (EMP_ID, EMP_NAME, SALARY)
        VALUES (302, 'Mid Employee', SALARY)

    ELSE
        INTO EMPLOYEE (EMP_ID, EMP_NAME, SALARY)
        VALUES (303, 'Junior Employee', SALARY)

SELECT 75000 AS SALARY
FROM DUAL;


/* ============================================================
   33. INSERT USING SEQUENCE
   ============================================================ */

CREATE SEQUENCE EMP_SEQ
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, EMAIL)
VALUES
    (EMP_SEQ.NEXTVAL, 'Sequence User', 'sequence@example.com');


/* ============================================================
   34. SEQUENCE WITH CACHE
   ============================================================ */

CREATE SEQUENCE ORDER_SEQ
START WITH 1
INCREMENT BY 1
CACHE 20;


/* ============================================================
   35. SEQUENCE NOCACHE / NOCYCLE
   ============================================================ */

CREATE SEQUENCE TEST_SEQ
START WITH 500
INCREMENT BY 5
NOCACHE
NOCYCLE;


/* ============================================================
   36. UPDATE - BASIC
   ============================================================ */

UPDATE EMPLOYEE
SET SALARY = 55000
WHERE EMP_ID = 101;


/* ============================================================
   37. UPDATE MULTIPLE COLUMNS
   ============================================================ */

UPDATE EMPLOYEE
SET
    SALARY = 65000,
    BONUS = 5000,
    IS_ACTIVE = 'Y'
WHERE EMP_ID = 102;


/* ============================================================
   38. UPDATE WITH EXPRESSION
   ============================================================ */

UPDATE EMPLOYEE
SET SALARY = SALARY * 1.10
WHERE DEPT_ID = 1;


/* ============================================================
   39. UPDATE WITH NULL
   ============================================================ */

UPDATE EMPLOYEE
SET BONUS = NULL
WHERE EMP_ID = 103;


/* ============================================================
   40. DELETE
   ============================================================ */

DELETE FROM EMPLOYEE
WHERE EMP_ID = 101;


/* ============================================================
   41. DELETE WITH CONDITION
   ============================================================ */

DELETE FROM EMPLOYEE
WHERE SALARY < 30000;


/* ============================================================
   42. MERGE / UPSERT
   ============================================================ */

MERGE INTO DEPARTMENT d
USING (
    SELECT 1 AS DEPT_ID,
           'Engineering Updated' AS DEPT_NAME,
           'Chennai' AS LOCATION
    FROM DUAL
) src
ON (d.DEPT_ID = src.DEPT_ID)

WHEN MATCHED THEN
    UPDATE SET
        d.DEPT_NAME = src.DEPT_NAME,
        d.LOCATION = src.LOCATION

WHEN NOT MATCHED THEN
    INSERT
        (DEPT_ID, DEPT_NAME, LOCATION)
    VALUES
        (src.DEPT_ID, src.DEPT_NAME, src.LOCATION);


/* ============================================================
   43. MERGE WITH CONDITIONAL UPDATE
   ============================================================ */

MERGE INTO EMPLOYEE e
USING (
    SELECT 101 AS EMP_ID,
           75000 AS SALARY
    FROM DUAL
) src
ON (e.EMP_ID = src.EMP_ID)

WHEN MATCHED THEN
    UPDATE SET
        e.SALARY = src.SALARY

WHEN NOT MATCHED THEN
    INSERT
        (EMP_ID, EMP_NAME, SALARY)
    VALUES
        (src.EMP_ID, 'New Employee', src.SALARY);


/* ============================================================
   44. EMPTY STRING EDGE CASE
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, EMAIL)
VALUES
    (401, '', '');


/* ============================================================
   45. SINGLE QUOTE ESCAPING
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, EMAIL)
VALUES
    (402, 'John''s Employee', 'john''s@example.com');


/* ============================================================
   46. SPECIAL CHARACTERS
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, DESCRIPTION)
VALUES
    (403, 'Test User', 'Line 1
Line 2
Line 3');


/* ============================================================
   47. UNICODE DATA
   ============================================================ */

INSERT INTO EMPLOYEE
    (EMP_ID, EMP_NAME, CITY)
VALUES
    (404, 'விக்னேஷ்', 'சென்னை');


/* ============================================================
   48. DATE LITERAL
   ============================================================ */

INSERT INTO DATE_TEST
    (ID, DATE_COL)
VALUES
    (1, DATE '2026-10-05');


/* ============================================================
   49. TIMESTAMP LITERAL
   ============================================================ */

INSERT INTO DATE_TEST
    (ID, TIMESTAMP_COL)
VALUES
    (2, TIMESTAMP '2026-10-05 14:30:00');


/* ============================================================
   50. TIMESTAMP WITH TIME ZONE
   ============================================================ */

INSERT INTO DATE_TEST
    (ID, TS_TZ_COL)
VALUES
    (
        3,
        TIMESTAMP '2026-10-05 14:30:00 +05:30'
    );


/* ============================================================
   51. RAW DATA
   ============================================================ */

INSERT INTO BINARY_TEST
    (ID, RAW_DATA)
VALUES
    (1, HEXTORAW('A1B2C3D4'));


/* ============================================================
   52. DROP INDEX
   ============================================================ */

DROP INDEX IDX_EMPLOYEE_NAME;


/* ============================================================
   53. DROP TABLE
   ============================================================ */

DROP TABLE EMPLOYEE_PROJECT;


/* ============================================================
   54. DROP TABLE CASCADE CONSTRAINTS
   ============================================================ */

DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;


/* ============================================================
   55. DROP SEQUENCE
   ============================================================ */

DROP SEQUENCE TEST_SEQ;


/* ============================================================
   56. RENAME TABLE
   ============================================================ */

RENAME DEPARTMENT TO COMPANY_DEPARTMENT;


/* ============================================================
   57. TRUNCATE TABLE
   ============================================================ */

TRUNCATE TABLE NUMBER_TEST;


/* ============================================================
   58. COMMENT ON TABLE
   ============================================================ */

COMMENT ON TABLE EMPLOYEE
IS 'Employee master information';


/* ============================================================
   59. COMMENT ON COLUMN
   ============================================================ */

COMMENT ON COLUMN EMPLOYEE.EMP_NAME
IS 'Full name of employee';


/* ============================================================
   60. GRANT / REVOKE
   ============================================================ */

GRANT SELECT, INSERT, UPDATE
ON EMPLOYEE
TO APP_USER;


REVOKE UPDATE
ON EMPLOYEE
FROM APP_USER;